stages:
  - check
  - build

image: registry.gitlab.com/kupfer/kupferbootstrap:dev
variables:
  GIT_CLONE_PATH: /builds
  ARCH: aarch64
before_script:
  - mkdir -p /kupfer/{pkgbuilds,packages,prebuilts} /root/.cache/kupfer
  - mount --bind /kupfer/{packages,prebuilts}
  - for dir in /pkgbuilds /prebuilts; do mkdir -p "$dir" && mount --bind /kupfer"$dir" "$dir"; done
  - mount --bind /kupfer /root/.cache/kupfer
  - cd /kupfer
  - cp -a /builds/. ./pkgbuilds/
  - kupferbootstrap config init -N

check_formatting:
  stage: check
  tags:
    - packages
  script:
    - kupferbootstrap packages check all

push_packages:
  stage: build
  tags:
    - packages
  only:
    - main
    - dev
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cd ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" > id_rsa.base64
    - openssl enc -d -base64 -A -in id_rsa.base64 -out id_rsa
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.email "kupfer@kupfer.cu"
    - git config --global user.name "Kupfer Bot"
    - cd /kupfer
    - git clone --depth=1 -b "$CI_COMMIT_BRANCH" git@gitlab.com:kupfer/packages/prebuilts.git packages
    - kupferbootstrap packages build all
    - cd packages
    - git add .
    - (git commit -m "$(../.gitlab/generate-commit-message.sh)" && git push) || true
