stages:
  - check
  - build

variables:
  GIT_CLONE_PATH: /builds
  LOGFILE: /builds/logs/kupferbootstrap.log
  ARCH: aarch64

default:
  image: registry.gitlab.com/kupfer/kupferbootstrap:dev
  before_script:
    - mkdir -p /kupfer/{pkgbuilds,packages,prebuilts} /root/.cache/kupfer "$(dirname "$LOGFILE")"
    - mount --bind /kupfer/{packages,prebuilts}
    - for dir in /pkgbuilds /prebuilts; do mkdir -p "$dir" && mount --bind /kupfer"$dir" "$dir"; done
    - mount --bind /kupfer /root/.cache/kupfer
    - cd /kupfer
    - cp -a /builds/. ./pkgbuilds/
    - kupferbootstrap config init -N
  artifacts: &logartifacts
    name: logs
    paths:
      - "$LOGFILE"
    expire_in: 30 days
    when: always

check_formatting:
  stage: check
  tags:
    - packages
  script:
    - script -e --log-out "$LOGFILE" -c 'kupferbootstrap packages check all'

.build:
  stage: build
  tags:
    - packages
  script: &build_script
    - cd /kupfer
    - git clone --depth=1 -b "$REPOBRANCH" https://gitlab.com/kupfer/packages/prebuilts.git packages
    - script -e --log-out "$LOGFILE" -c 'kupferbootstrap packages clean --force'
    - script -e --log-out "$LOGFILE" -c 'kupferbootstrap packages build all'
    - 'cd ./pkgbuilds && ./.gitlab/check_modified.sh'

build_packages:
  variables:
    REPOBRANCH: dev
  extends: .build
  only:
    refs:
      - branches
    changes:
      - '[a-z]*/*/*'
  except:
    - main
    - dev
  after_script:
    - cd /kupfer/packages
    - for p in $(git ls-files --others --exclude-standard) ; do echo "copying $p" ; install -Dm644 "$p" "$GIT_CLONE_PATH/packages/$p" ; done
  artifacts:
    <<: *logartifacts
    name: artifacts
    paths:
      - "$LOGFILE"
      - "packages/*/*/*.*"

push_packages:
  variables:
    REPOBRANCH: "$CI_COMMIT_BRANCH"
  extends: .build
  tags:
    - packages
  only:
    - main
    - dev
  script:
    - *build_script
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cd ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" > id_rsa.base64
    - openssl enc -d -base64 -A -in id_rsa.base64 -out id_rsa
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.email "kupfer@kupfer.cu"
    - git config --global user.name "Kupfer Bot"
    - cd /kupfer/packages
    - git remote set-url origin git@gitlab.com:kupfer/packages/prebuilts.git
    - (git ls-files --others --exclude-standard | grep '\.pkg\.' | xargs -r dirname | xargs -r git add) || echo "apparently no packages to upload."
    # try pushing twice since pushing occasionally fails, which can be painful after a long build
    - git commit -m "$("$GIT_CLONE_PATH"/.gitlab/generate-commit-message.sh)" ; (git push || git push)
